### ISSUE TITLE
Exit code change from 1 to 0

### ISSUE THREAD

**Issue by AnaisUrlichs** [morwn/SC-Workshop#2]
The exit code in the workflow has to be 0 because you are then asking people to change it to 1:

```
    - name: Run secret scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "fs"
        format: 'table'
        exit-code: '1'
        scanners: 'secret'
```
